const orderDetail = {
  "branchid": 2,
  "branchname": "饭团(海源学院总店)",
  "deliveryfee": 1.0,
  "discount": 4.5,
  "disservice": "商家自行配送",
  "exptime": "立即配送",
  "firstorder": 3.0,
  "hour": "20:01",
  "iscomplete": 0,
  "ismember": 1,
  "openid": "oM_GB4rjG6k2dKlqXxrBb_0fdAWI",
  "orderItems": [{
    "imagepath": "/static/fantuan/szb/szb.jpg",
    "ismeal": 1,
    "memberprice": 3.5,
    "name": "手抓饼",
    "number": 1,
    "orderItems": [{
      "imagepath": "/static/fantuan/szb/pg.jpg",
      "ismeal": 0,
      "memberprice": 2.0,
      "name": "培根",
      "number": 1,
      "orderItems": [],
      "orderid": 42,
      "price": 2.0,
      "productid": 16
    }, {
      "imagepath": "/static/fantuan/szb/jp.jpg",
      "ismeal": 0,
      "memberprice": 4.0,
      "name": "鸡排",
      "number": 1,
      "orderItems": [],
      "orderid": 42,
      "price": 4.0,
      "productid": 17
    }, {
      "imagepath": "/static/fantuan/szb/jjd.jpg",
      "ismeal": 0,
      "memberprice": 1.5,
      "name": "煎鸡蛋",
      "number": 1,
      "orderItems": [],
      "orderid": 42,
      "price": 1.5,
      "productid": 24
    }, {
      "imagepath": "/static/fantuan/szb/jl.jpg",
      "ismeal": 0,
      "memberprice": 2.0,
      "name": "鸡柳",
      "number": 1,
      "orderItems": [],
      "orderid": 42,
      "price": 2.0,
      "productid": 14
    }, {
      "imagepath": "/static/fantuan/szb/rg.jpg",
      "ismeal": 0,
      "memberprice": 2.0,
      "name": "热狗",
      "number": 1,
      "orderItems": [],
      "orderid": 42,
      "price": 2.0,
      "productid": 15
    }],
    "orderid": 42,
    "price": 4.0,
    "productid": 13
  }, {
    "imagepath": "/static/fantuan/twft/eeljrft.jpg",
    "ismeal": 0,
    "memberprice": 8.0,
    "name": "奥尔良鸡肉饭团",
    "number": 1,
    "orderItems": [],
    "orderid": 42,
    "price": 9.0,
    "productid": 3
  }],
  "orderid": 42,
  "orderno": "15878142739396369673124817388154",
  "ordertime": "2020-04-25 19:31:42",
  "paym": "在线支付",
  "totalfee": 21.0,
  "uaddress": {
    "area": "天骄北麓19幢",
    "buildtime": "2020-04-21 23:30:33",
    "children": [],
    "detailed": "3109",
    "gender": "先生",
    "id": 31,
    "latitude": 25.1151,
    "longitude": 102.731,
    "name": "严",
    "new": false,
    "odr": 0,
    "parent": {},
    "phone": "13888563741",
    "userid": 7
  }
}

module.exports = orderDetail