const pack = {
  "bproductsitems": [{
    "bproductsitems": [],
    "branchid": 2,
    "buildtime": "2020-04-14 23:36:24",
    "businessid": 1,
    "categoryid": 3,
    "children": [],
    "id": 14,
    "imagepath": "/static/fantuan/szb/jl.jpg",
    "memberprice": 0.0,
    "name": "鸡柳",
    "new": false,
    "num": 0,
    "odr": 14,
    "packages": "0",
    "parent": {},
    "pid": 13,
    "price": 2.0
  }, {
    "bproductsitems": [],
    "branchid": 2,
    "buildtime": "2020-04-14 23:36:24",
    "businessid": 1,
    "categoryid": 3,
    "children": [],
    "id": 15,
    "imagepath": "/static/fantuan/szb/rg.jpg",
    "memberprice": 0.0,
    "name": "热狗",
    "new": false,
    "num": 0,
    "odr": 15,
    "packages": "0",
    "parent": {},
    "pid": 13,
    "price": 2.0
  }, {
    "bproductsitems": [],
    "branchid": 2,
    "buildtime": "2020-04-14 23:36:24",
    "businessid": 1,
    "categoryid": 3,
    "children": [],
    "id": 16,
    "imagepath": "/static/fantuan/szb/pg.jpg",
    "memberprice": 0.0,
    "name": "培根",
    "new": false,
    "num": 0,
    "odr": 16,
    "packages": "0",
    "parent": {},
    "pid": 13,
    "price": 2.0
  }, {
    "bproductsitems": [],
    "branchid": 2,
    "buildtime": "2020-04-14 23:36:24",
    "businessid": 1,
    "categoryid": 3,
    "children": [],
    "id": 17,
    "imagepath": "/static/fantuan/szb/jp.jpg",
    "memberprice": 0.0,
    "name": "鸡排",
    "new": false,
    "num": 0,
    "odr": 17,
    "packages": "0",
    "parent": {},
    "pid": 13,
    "price": 4.0
  }, {
    "bproductsitems": [],
    "branchid": 2,
    "buildtime": "2020-04-14 23:45:48",
    "businessid": 1,
    "categoryid": 3,
    "children": [],
    "id": 24,
    "imagepath": "/static/fantuan/szb/jjd.jpg",
    "memberprice": 0.0,
    "name": "煎鸡蛋",
    "new": false,
    "num": 0,
    "odr": 24,
    "packages": "0",
    "parent": {},
    "pid": 13,
    "price": 1.5
  }],
  "branchid": 2,
  "buildtime": "2020-04-14 23:36:24",
  "businessid": 1,
  "categoryid": 3,
  "children": [],
  "id": 13,
  "imagepath": "/static/fantuan/szb/szb.jpg",
  "memberprice": 3.5,
  "name": "手抓饼",
  "new": false,
  "note": "组合套餐",
  "num": 0,
  "odr": 13,
  "packages": "1",
  "parent": {},
  "price": 4.0
}


module.exports = pack;